---
title: "Koo jae kwan"
output:
  html_document:
    df_print: paged
---

```{r}
simpson_n <- function(ftn, a, b, n = 100) {
  n <- max(c(2*(n %/% 2), 4))
  h <- (b-a)/n
  x.vec1 <- seq(a+h, b-h, by = 2*h)
  x.vec2 <- seq(a+2*h, b-2*h, by = 2*h)
  f.vec1 <- sapply(x.vec1, ftn)
  f.vec2 <- sapply(x.vec2, ftn)
  h/3*(ftn(a) + ftn(b) + 4*sum(f.vec1) + 2*sum(f.vec2)) # return value
}
```
```{r}
c <- 1/simpson_n(function(x) exp(-x^3), 0, 1, n=1000)
f <- function(x) {
  if (0 <= x & x <= 1) c*exp(-x^3)
  else 0
}
```
```{r}
Fx<-function(x){
  if(0 <= x & x <= 1) {
    return(simpson_n(f,0,x))
  }else if(x<0){
    return(0)
  }else{
    return(1)
  }
}
x<-seq(-1,2,0.01)

plot(x,sapply(x,Fx),type="l", ylab="F")
```
```{r}
inverse <- function (f, lower = 0, upper = 1) {
function (y) uniroot((function (x) f(x) - y), lower = lower, upper = upper)[[1]]
}
qx <- inverse(Fx)
```
```{r}
y <- seq(0,1,0.01)
plot(y, sapply(y, qx), type = 'l', ylab="q", xlab="x")
```
```{r}
koo<-c()
for(i in 1:10000){
  koo[i]<-qx(runif(1))
}
hist(koo,probability = T,xlab="x",main="Histogram of x")
lines(seq(0,1,0.01),sapply(seq(0,1,0.01),f))
```
```{r}
hist(koo,probability = T,xlab="x",main="Histogram of x")
lines(density(koo))
```



